### ISSUE TITLE
Build and deployment process

### ISSUE THREAD

**Issue by onlinejudge95** [knro/indiwebmanager#64]
Can we automate the build process of this package using any CI provider?

I checked the `.travis.yml` file and was not able to find any `build/deployment` step.
I had recently merged an MR and i am not able to see the bumped version in pypi. Adding this functionality would make the package update process better.

**Comment by setnes** [comment]
This might not be what you're looking for, but here's an Ansible task that installs into a Python virtual environment at /opt/indiweb/venv.  This requires virtualenv to be installed on the target system.  If you're using systemd to start the service, you'd have to adjust the instructions to point at the virtual environment.

A few notes on this.  The most recent changes that allow this to be installed on Ubuntu 24.04 have not yet been published to PyPi (??), so that's why this is pulling directly from github.  Also, ansible.builtin.pip does nothing with requirements.txt from the git source.  It takes some extra magic to run that and get the desired versions for the dependencies.  In this case I'm pulling requirements.txt directly from github in the extra_args parameter.  I'm not entirely sure how to reference that file directly from what ansible.builtin.pip downloads with the *.git link.  That gets created and destroyed as part of whatever the ansible module is doing.  So that file really gets downloaded twice.

Installing into the virtual environment like this allows us to use whatever versions are required without ending up in dependency hell by trying to use whatever the versions the OS has installed.  It is a pain, but it also makes using this on different platforms a lot more predictable.

```
- name: Install INDI Web Manager
  ansible.builtin.pip:
    name: "git+https://github.com/knro/indiwebmanager.git@master"
    state: latest
    virtualenv: "/opt/indiweb/venv"
    extra_args: "-r https://raw.githubusercontent.com/knro/indiwebmanager/refs/heads/master/requirements.txt"
  register: pip_output
```

I'm not sure if upgrades will work automatically as there's not really a version change to watch for when pulling from git master like this.
